https://discourse.onlinedegree.iitm.ac.in/t/164277

I am getting the following error</p>
<pre><code class="lang-auto">Traceback (most recent call last):
  File "/var/folders/rj/z_3b8hl51558519w90k5hp600000gn/T/datagen4COEF3.py", line 284, in &lt;module&gt;
    os.makedirs(config["root"], exist_ok=True)
    ~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "&lt;frozen os&gt;", line 227, in makedirs
OSError: [Errno 30] Read-only file system: '/data'
</code></pre>
<p>If i can’t automate this process, i don’t see the point writing code for other tasks. Can anyone help me solving this error?</p><hr>

<h4>21f2000709 (#140)</h4>
<p>Has anyone succeeded in the extraction of credit cards details task? The LLM seems to consider it as illegal task and if I use pytessaract the docker image size will become really large. What to do in this case?</p>
<p><a class="mention" href="/u/carlton">@carlton</a> <a class="mention" href="/u/jivraj">@Jivraj</a></p><hr>

<h4>22f3001307 (#139)</h4>
<p>I am getting the same error.