https://discourse.onlinedegree.iitm.ac.in/t/171141

I have created a safe_open function that will throw a HTTP_403_FORBIDDEN error when tried to access files outside that directory. Because of this all the tasks failed. There also might be environment and configuration issues in my Dockerfile. When I tested locally, it worked fine but because of this small mistake I am now only getting 1/20. Is it possible to change/modify my code?</p>
<p>Thanks for considering, any help would be appreciated. Worked very hard for this</p><hr>

<h4>22f3002723 (#138)</h4>
<p>on a side note, to validate and test our docker/podman images on a platform outside of our dev environment we can use <a href="https://labs.play-with-docker.com/" rel="noopener nofollow ugc">https://labs.play-with-docker.com/</a>..